""" Material tags: air-like, solid, plant, misc and dirt. """
# Imports
from stewbeet import Mem, write_tag


# Functions
def write_material_tags() -> None:
	ns: str = Mem.ctx.project_id
	version: str = Mem.ctx.project_version

	# Write block tags
	write_tag(f"{ns}:v{version}/air", Mem.ctx.data.block_tags, values=[
		"#minecraft:banners",
		"#minecraft:buttons",
		"#minecraft:wool_carpets",
		"#minecraft:corals",
		"#minecraft:wooden_doors",
		"#minecraft:flower_pots",
		"#minecraft:beds",
		"#minecraft:leaves",
		"#minecraft:rails",
		"#minecraft:wooden_pressure_plates",
		"#minecraft:wooden_trapdoors",
		"#minecraft:signs",
		"#minecraft:fences",
		"#minecraft:candle_cakes",
		"#minecraft:candles",
		"minecraft:air",
		"minecraft:cave_air",
		"minecraft:void_air",
		"minecraft:light",
		"minecraft:structure_void",
		f"#{ns}:v{version}/plant",
		f"#{ns}:v{version}/fence_gate",
		f"#{ns}:v{version}/stained_glass_pane",
		"minecraft:cobweb",
		"minecraft:torch",
		"minecraft:wall_torch",
		"minecraft:end_rod",
		"minecraft:ladder",
		"minecraft:snow",
		"minecraft:cake",
		"minecraft:iron_bars",
		"minecraft:glass_pane",
		"minecraft:lever",
		"minecraft:stone_pressure_plate",
		"minecraft:light_weighted_pressure_plate",
		"minecraft:heavy_weighted_pressure_plate",
		"minecraft:repeater",
		"minecraft:comparator",
		"minecraft:redstone_wire",
		"minecraft:redstone_torch",
		"minecraft:redstone_wall_torch",
		"minecraft:tripwire_hook",
		"minecraft:conduit",
		"minecraft:turtle_egg",
		"minecraft:fire",
		"minecraft:barrier",
		"minecraft:cocoa",
		"minecraft:lantern",
		"minecraft:soul_lantern",
		"minecraft:scaffolding",
		"minecraft:tripwire",
		"#minecraft:chains",
		"minecraft:small_amethyst_bud",
		"minecraft:medium_amethyst_bud",
		"minecraft:large_amethyst_bud",
		"minecraft:lightning_rod",
		"minecraft:frogspawn",
		"minecraft:sculk_vein",
		"minecraft:nether_portal",
		"minecraft:end_portal"
	])

	write_tag(f"{ns}:v{version}/solid", Mem.ctx.data.block_tags, values=[
		"#minecraft:wool",
		"#minecraft:anvil",
		"#minecraft:coral_blocks",
		"#minecraft:logs",
		"#minecraft:planks",
		"#minecraft:bamboo_blocks",
		f"#{ns}:v{version}/concrete",
		f"#{ns}:v{version}/concrete_powder",
		f"#{ns}:v{version}/terracotta",
		f"#{ns}:v{version}/stones",
		f"#{ns}:v{version}/ores",
		f"#{ns}:v{version}/dirt",
		f"#{ns}:v{version}/mud",
		f"#{ns}:v{version}/misc"
	])

	write_tag(f"{ns}:v{version}/plant", Mem.ctx.data.block_tags, values=[
		"#minecraft:crops",
		"#minecraft:flowers",
		"#minecraft:saplings",
		"#minecraft:flowers",
		"#minecraft:cave_vines",
		"#minecraft:replaceable",
		"#minecraft:leaves",
		"minecraft:short_grass",
		"minecraft:tall_grass",
		"minecraft:seagrass",
		"minecraft:tall_seagrass",
		"minecraft:fern",
		"minecraft:large_fern",
		"minecraft:kelp",
		"minecraft:kelp_plant",
		"minecraft:lily_pad",
		"minecraft:sugar_cane",
		"minecraft:vine",
		"minecraft:glow_lichen",
		"minecraft:twisting_vines",
		"minecraft:twisting_vines_plant",
		"minecraft:weeping_vines",
		"minecraft:weeping_vines_plant",
		"minecraft:hanging_roots",
		"minecraft:spore_blossom",
		"minecraft:moss_carpet",
		"minecraft:bamboo",
		"minecraft:bamboo_sapling",
		"minecraft:azalea",
		"minecraft:flowering_azalea",
		"minecraft:dead_bush",
		"minecraft:small_dripleaf",
		"minecraft:big_dripleaf",
		"minecraft:big_dripleaf_stem",
		"minecraft:crimson_fungus",
		"minecraft:warped_fungus",
		"minecraft:crimson_roots",
		"minecraft:warped_roots",
		"minecraft:nether_sprouts"
	])

	write_tag(f"{ns}:v{version}/misc", Mem.ctx.data.block_tags, values=[
		"#minecraft:dragon_immune",
		"#minecraft:beacon_base_blocks",
		"#minecraft:campfires",
		"#minecraft:climbable",
		"#minecraft:infiniburn_overworld",
		"#minecraft:gold_ores",
		"#minecraft:iron_ores",
		"minecraft:netherrack",
		"minecraft:soul_sand",
		"minecraft:soul_soil",
		"minecraft:spawner",
		"minecraft:crying_obsidian",
		"minecraft:end_stone",
		"minecraft:chorus_plant",
		"minecraft:chorus_flower",
		"minecraft:crafting_table",
		"minecraft:enchanting_table",
		"minecraft:brewing_stand",
		"minecraft:chest",
		"minecraft:ender_chest",
		"minecraft:piston",
		"minecraft:sticky_piston",
		"minecraft:dispenser",
		"minecraft:dropper",
		"minecraft:hopper",
		"minecraft:grindstone",
		"minecraft:lectern",
		"minecraft:respawn_anchor",
		"minecraft:smoker"
	])

	write_tag(f"{ns}:v{version}/dirt", Mem.ctx.data.block_tags, values=[
		"#minecraft:dirt",
		"#minecraft:sand",
		"minecraft:gravel",
		"minecraft:clay",
		"minecraft:farmland",
		"minecraft:dirt_path",
		"minecraft:podzol",
		"minecraft:mycelium",
		"minecraft:rooted_dirt",
		"minecraft:mud",
		"minecraft:muddy_mangrove_roots",
		"minecraft:packed_mud",
		"minecraft:suspicious_sand",
		"minecraft:suspicious_gravel",
		"minecraft:soul_sand",
		"minecraft:soul_soil",
		"minecraft:crimson_nylium",
		"minecraft:warped_nylium",
		"minecraft:sculk_catalyst"
	])

