""" Surface tags: activatable blocks, terracotta, stones and stained glass. """
# Imports
from stewbeet import Mem, write_tag


# Functions
def write_surface_tags() -> None:
	ns: str = Mem.ctx.project_id
	version: str = Mem.ctx.project_version

	write_tag(f"{ns}:v{version}/activate", Mem.ctx.data.block_tags, values=[
		"minecraft:lever",
		"minecraft:stone_button",
		"minecraft:polished_blackstone_button"
	])

	write_tag(f"{ns}:v{version}/terracotta", Mem.ctx.data.block_tags, values=[
		"minecraft:terracotta",
		"minecraft:white_terracotta",
		"minecraft:orange_terracotta",
		"minecraft:magenta_terracotta",
		"minecraft:light_blue_terracotta",
		"minecraft:yellow_terracotta",
		"minecraft:lime_terracotta",
		"minecraft:pink_terracotta",
		"minecraft:gray_terracotta",
		"minecraft:light_gray_terracotta",
		"minecraft:cyan_terracotta",
		"minecraft:purple_terracotta",
		"minecraft:blue_terracotta",
		"minecraft:brown_terracotta",
		"minecraft:green_terracotta",
		"minecraft:red_terracotta",
		"minecraft:black_terracotta",
		"minecraft:bricks",
		"minecraft:brick_slab",
		"minecraft:brick_stairs",
		"minecraft:brick_wall",
		"minecraft:nether_bricks",
		"minecraft:cracked_nether_bricks",
		"minecraft:nether_brick_slab",
		"minecraft:nether_brick_stairs",
		"minecraft:nether_brick_wall",
		"minecraft:nether_brick_fence",
		"minecraft:red_nether_bricks",
		"minecraft:red_nether_brick_slab",
		"minecraft:red_nether_brick_stairs",
		"minecraft:red_nether_brick_wall",
		"minecraft:end_stone_bricks",
		"minecraft:end_stone_brick_slab",
		"minecraft:end_stone_brick_stairs",
		"minecraft:end_stone_brick_wall",
		"minecraft:prismarine_bricks",
		"minecraft:prismarine_brick_slab",
		"minecraft:prismarine_brick_stairs"
	])

	write_tag(f"{ns}:v{version}/stones", Mem.ctx.data.block_tags, values=[
		"#minecraft:stone_bricks",
		"#minecraft:deepslate_ore_replaceables",
		"#minecraft:base_stone_overworld",
		"#minecraft:base_stone_nether",
		"minecraft:stone",
		"minecraft:stone_slab",
		"minecraft:stone_stairs",
		"minecraft:cobblestone",
		"minecraft:cobblestone_slab",
		"minecraft:cobblestone_stairs",
		"minecraft:cobblestone_wall",
		"minecraft:mossy_cobblestone",
		"minecraft:mossy_cobblestone_slab",
		"minecraft:mossy_cobblestone_stairs",
		"minecraft:mossy_cobblestone_wall",
		"minecraft:diorite",
		"minecraft:diorite_slab",
		"minecraft:diorite_stairs",
		"minecraft:diorite_wall",
		"minecraft:polished_diorite",
		"minecraft:polished_diorite_slab",
		"minecraft:polished_diorite_stairs",
		"minecraft:granite",
		"minecraft:granite_slab",
		"minecraft:granite_stairs",
		"minecraft:granite_wall",
		"minecraft:polished_granite",
		"minecraft:polished_granite_slab",
		"minecraft:polished_granite_stairs",
		"minecraft:andesite",
		"minecraft:andesite_slab",
		"minecraft:andesite_stairs",
		"minecraft:andesite_wall",
		"minecraft:polished_andesite",
		"minecraft:polished_andesite_slab",
		"minecraft:polished_andesite_stairs",
		"minecraft:deepslate",
		"minecraft:deepslate_tiles",
		"minecraft:cracked_deepslate_tiles",
		"minecraft:deepslate_tile_slab",
		"minecraft:deepslate_tile_stairs",
		"minecraft:deepslate_tile_wall",
		"minecraft:deepslate_bricks",
		"minecraft:cracked_deepslate_bricks",
		"minecraft:deepslate_brick_slab",
		"minecraft:deepslate_brick_stairs",
		"minecraft:deepslate_brick_wall",
		"minecraft:chiseled_deepslate",
		"minecraft:cobbled_deepslate",
		"minecraft:cobbled_deepslate_slab",
		"minecraft:cobbled_deepslate_stairs",
		"minecraft:cobbled_deepslate_wall",
		"minecraft:polished_deepslate",
		"minecraft:polished_deepslate_slab",
		"minecraft:polished_deepslate_stairs",
		"minecraft:polished_deepslate_wall",
		"minecraft:blackstone",
		"minecraft:blackstone_slab",
		"minecraft:blackstone_stairs",
		"minecraft:blackstone_wall",
		"minecraft:polished_blackstone",
		"minecraft:polished_blackstone_slab",
		"minecraft:polished_blackstone_stairs",
		"minecraft:polished_blackstone_wall",
		"minecraft:polished_blackstone_bricks",
		"minecraft:cracked_polished_blackstone_bricks",
		"minecraft:polished_blackstone_brick_slab",
		"minecraft:polished_blackstone_brick_stairs",
		"minecraft:polished_blackstone_brick_wall"
	])

	write_tag(f"{ns}:v{version}/stained_glass_pane", Mem.ctx.data.block_tags, values=[
		"minecraft:white_stained_glass_pane",
		"minecraft:orange_stained_glass_pane",
		"minecraft:magenta_stained_glass_pane",
		"minecraft:light_blue_stained_glass_pane",
		"minecraft:yellow_stained_glass_pane",
		"minecraft:lime_stained_glass_pane",
		"minecraft:pink_stained_glass_pane",
		"minecraft:gray_stained_glass_pane",
		"minecraft:light_gray_stained_glass_pane",
		"minecraft:cyan_stained_glass_pane",
		"minecraft:purple_stained_glass_pane",
		"minecraft:blue_stained_glass_pane",
		"minecraft:brown_stained_glass_pane",
		"minecraft:green_stained_glass_pane",
		"minecraft:red_stained_glass_pane",
		"minecraft:black_stained_glass_pane",
		"minecraft:glass_pane",
		"minecraft:iron_bars"
	])

