""" Sidearm stat tables, including the Ray Gun. """
# Imports
from stewbeet import JsonDict

from ..casings import CASING_9X18MM, CASING_9X19MM, CASING_32ACP, CASING_45ACP, CASING_50AE
from ..keys import (
	ACCURACY_BASE,
	ACCURACY_JUMP,
	ACCURACY_SNEAK,
	ACCURACY_SPRINT,
	ACCURACY_WALK,
	BASE_WEAPON,
	BURST,
	CAN_AUTO,
	CAN_BURST,
	CAPACITY,
	CASING_BINORMAL,
	CASING_MODEL,
	CASING_NORMAL,
	CASING_OFFSET,
	CASING_TANGENT,
	COOLDOWN,
	DAMAGE,
	DECAY,
	EXPLOSION_DAMAGE,
	EXPLOSION_DECAY,
	EXPLOSION_RADIUS,
	FIRE_MODE,
	KICK,
	PAP_NAME,
	PAP_STATS,
	PROJECTILE_GRAVITY,
	PROJECTILE_LIFETIME,
	PROJECTILE_MODEL,
	PROJECTILE_SPEED,
	RELOAD_END,
	RELOAD_TIME,
	REMAINING_BULLETS,
	SWITCH,
	WEIGHT,
)
from ..sounds import GUN_SOUNDS, gun_sounds

# Constants
# Pistols
M1911: JsonDict = {
	"stats": {
		BASE_WEAPON: "m1911", FIRE_MODE: "semi",
		CAPACITY: 7, RELOAD_TIME: 45, RELOAD_END: 10, DAMAGE: 11, DECAY: 0.88, WEIGHT: 0,
		ACCURACY_BASE: 165, ACCURACY_SNEAK: 105, ACCURACY_WALK: 250, ACCURACY_SPRINT: 450, ACCURACY_JUMP: 800,
		SWITCH: 10, KICK: 4, CASING_MODEL: CASING_45ACP, CASING_NORMAL: 250, CASING_TANGENT: 0, CASING_BINORMAL: -150,
		CASING_OFFSET: {"normal": (-0.33, -0.25, 0.5), "zoom": (-0.05, -0.05, 0.4)},
		PAP_STATS: {
			PAP_NAME: "Mustang and Sally",
			CAPACITY: 12,
			REMAINING_BULLETS: 12,
			RELOAD_TIME: 32,
			RELOAD_END: 8,
			COOLDOWN: 4,
			ACCURACY_BASE: 120,
			ACCURACY_WALK: 190,
			ACCURACY_SPRINT: 340,
			SWITCH: 8,
			PROJECTILE_SPEED: 2000,
			PROJECTILE_GRAVITY: 15,
			PROJECTILE_LIFETIME: 60,
			PROJECTILE_MODEL: "m1911",
			EXPLOSION_RADIUS: 2.5,
			EXPLOSION_DAMAGE: 24,
			EXPLOSION_DECAY: 0.75,
			DAMAGE: [22, 26, 31, 37, 44],
		},
	},
	"sounds": gun_sounds("m1911", *GUN_SOUNDS, crack="tiny")
}

M9: JsonDict = {
	"stats": {
		BASE_WEAPON: "m9", FIRE_MODE: "semi",
		CAPACITY: 15, RELOAD_TIME: 60, RELOAD_END: 15, DAMAGE: 9, DECAY: 0.92, WEIGHT: 6,
		ACCURACY_BASE: 130, ACCURACY_SNEAK: 75, ACCURACY_WALK: 160, ACCURACY_SPRINT: 400, ACCURACY_JUMP: 800,
		SWITCH: 10, KICK: 3, CASING_MODEL: CASING_9X19MM, CASING_NORMAL: 100, CASING_TANGENT: -75, CASING_BINORMAL: -150,
		CASING_OFFSET: {"normal": (-0.35, -0.25, 0.5), "zoom": (-0.05, -0.1, 0.4)},
		PAP_STATS: {
			PAP_NAME: "Beretta M9",
			CAPACITY: 21,
			REMAINING_BULLETS: 21,
			RELOAD_TIME: 45,
			RELOAD_END: 10,
			ACCURACY_BASE: 100,
			ACCURACY_WALK: 130,
			ACCURACY_SPRINT: 300,
			ACCURACY_JUMP: 600,
			SWITCH: 8,
			DAMAGE: [18, 21, 25, 30, 36],
		},
	},
	"sounds": gun_sounds("m9", *GUN_SOUNDS, crack="tiny")
}

DEAGLE: JsonDict = {
	"stats": {
		BASE_WEAPON: "deagle", FIRE_MODE: "semi",
		CAPACITY: 7, RELOAD_TIME: 70, RELOAD_END: 15, COOLDOWN: 3, DAMAGE: 17, DECAY: 0.90, WEIGHT: 6,
		ACCURACY_BASE: 220, ACCURACY_SNEAK: 50, ACCURACY_WALK: 400, ACCURACY_SPRINT: 1000, ACCURACY_JUMP: 2000,
		SWITCH: 15, KICK: 5, CASING_MODEL: CASING_50AE, CASING_NORMAL: 250, CASING_TANGENT: -75, CASING_BINORMAL: -100,
		CASING_OFFSET: {"normal": (-0.3, -0.2, 0.5), "zoom": (-0.05, -0.05, 0.4)},
		PAP_STATS: {
			PAP_NAME: "Space Eagle",
			CAPACITY: 10,
			REMAINING_BULLETS: 10,
			RELOAD_TIME: 55,
			RELOAD_END: 10,
			COOLDOWN: 2,
			ACCURACY_BASE: 170,
			ACCURACY_WALK: 280,
			ACCURACY_SPRINT: 650,
			ACCURACY_JUMP: 1200,
			SWITCH: 12,
			DAMAGE: [34, 40, 47, 55, 64],
		},
	},
	"sounds": gun_sounds("deagle", *GUN_SOUNDS, crack="tiny")
}

MAKAROV: JsonDict = {
	"stats": {
		BASE_WEAPON: "makarov", FIRE_MODE: "semi",
		CAPACITY: 8, RELOAD_TIME: 40, RELOAD_END: 10, DAMAGE: 9, DECAY: 0.90, WEIGHT: 6,
		ACCURACY_BASE: 120, ACCURACY_SNEAK: 65, ACCURACY_WALK: 130, ACCURACY_SPRINT: 350, ACCURACY_JUMP: 800,
		SWITCH: 8, KICK: 2, CASING_MODEL: CASING_9X18MM, CASING_NORMAL: 250, CASING_TANGENT: -100, CASING_BINORMAL: -75,
		CASING_OFFSET: {"normal": (-0.3, -0.25, 0.5), "zoom": (-0.05, -0.05, 0.4)},
		PAP_STATS: {
			PAP_NAME: "Mak-A-Roar",
			CAPACITY: 12,
			REMAINING_BULLETS: 12,
			RELOAD_TIME: 30,
			RELOAD_END: 8,
			ACCURACY_BASE: 95,
			ACCURACY_WALK: 105,
			ACCURACY_SPRINT: 250,
			ACCURACY_JUMP: 500,
			SWITCH: 6,
			DAMAGE: [18, 21, 25, 30, 36],
		},
	},
	"sounds": gun_sounds("makarov", *GUN_SOUNDS, crack="tiny")
}

GLOCK17: JsonDict = {
	"stats": {
		BASE_WEAPON: "glock17", FIRE_MODE: "semi",
		CAPACITY: 17, RELOAD_TIME: 60, RELOAD_END: 16, DAMAGE: 9, DECAY: 0.92, WEIGHT: 6,
		ACCURACY_BASE: 150, ACCURACY_SNEAK: 90, ACCURACY_WALK: 170, ACCURACY_SPRINT: 400, ACCURACY_JUMP: 800,
		SWITCH: 8, KICK: 3, CASING_MODEL: CASING_9X19MM, CASING_NORMAL: 225, CASING_TANGENT: -100, CASING_BINORMAL: -75,
		CASING_OFFSET: {"normal": (-0.35, -0.27, 0.5), "zoom": (-0.05, 0.0, 0.4)},
		PAP_STATS: {
			PAP_NAME: "Glock 'n' Load",
			CAPACITY: 24,
			REMAINING_BULLETS: 24,
			RELOAD_TIME: 44,
			RELOAD_END: 10,
			ACCURACY_BASE: 110,
			ACCURACY_WALK: 130,
			ACCURACY_SPRINT: 280,
			ACCURACY_JUMP: 500,
			SWITCH: 6,
			DAMAGE: [18, 21, 25, 30, 36],
		},
	},
	"sounds": gun_sounds("glock17", *GUN_SOUNDS, crack="tiny")
}

GLOCK18: JsonDict = {
	"stats": {
		BASE_WEAPON: "glock18", FIRE_MODE: "auto",
		CAPACITY: 19, RELOAD_TIME: 70, RELOAD_END: 16, COOLDOWN: 1, BURST: 4, CAN_BURST: True, CAN_AUTO: True, DAMAGE: 9, DECAY: 0.92, WEIGHT: 5,
		ACCURACY_BASE: 180, ACCURACY_SNEAK: 140, ACCURACY_WALK: 300, ACCURACY_SPRINT: 400, ACCURACY_JUMP: 800,
		SWITCH: 10, KICK: 3, CASING_MODEL: CASING_9X19MM, CASING_NORMAL: 225, CASING_TANGENT: -100, CASING_BINORMAL: -75,
		CASING_OFFSET: {"normal": (-0.35, -0.27, 0.5), "zoom": (-0.05, 0.0, 0.4)},
		PAP_STATS: {
			PAP_NAME: "The Panic Button",
			CAPACITY: 28,
			REMAINING_BULLETS: 28,
			RELOAD_TIME: 52,
			RELOAD_END: 10,
			ACCURACY_BASE: 130,
			ACCURACY_WALK: 220,
			ACCURACY_SPRINT: 280,
			ACCURACY_JUMP: 500,
			SWITCH: 8,
			DAMAGE: [18, 21, 25, 30, 36],
		},
	},
	"sounds": gun_sounds("glock18", *GUN_SOUNDS, crack="tiny")
}

VZ61: JsonDict = {
	"stats": {
		BASE_WEAPON: "vz61", FIRE_MODE: "auto",
		CAPACITY: 20, RELOAD_TIME: 70, RELOAD_END: 14, COOLDOWN: 2, BURST: 2, CAN_BURST: True, CAN_AUTO: True, DAMAGE: 8, DECAY: 0.92, WEIGHT: 7,
		ACCURACY_BASE: 150, ACCURACY_SNEAK: 80, ACCURACY_WALK: 290, ACCURACY_SPRINT: 400, ACCURACY_JUMP: 800,
		SWITCH: 12, KICK: 2, CASING_MODEL: CASING_32ACP, CASING_NORMAL: 300, CASING_TANGENT: 25, CASING_BINORMAL: 0,
		CASING_OFFSET: {"normal": (-0.23, -0.1, 0.5), "zoom": (0, 0.05, 0.4)},
		PAP_STATS: {
			PAP_NAME: "Skorpitron",
			CAPACITY: 28,
			REMAINING_BULLETS: 28,
			RELOAD_TIME: 52,
			RELOAD_END: 10,
			COOLDOWN: 1,
			ACCURACY_BASE: 120,
			ACCURACY_WALK: 210,
			ACCURACY_SPRINT: 280,
			ACCURACY_JUMP: 500,
			SWITCH: 8,
			DAMAGE: [16, 19, 23, 28, 34],
		},
	},
	"sounds": gun_sounds("vz61", *GUN_SOUNDS, crack="tiny")
}

RAY_GUN: JsonDict = {
	"stats": {
		BASE_WEAPON: "ray_gun", FIRE_MODE: "auto",
		CAPACITY: 20, RELOAD_TIME: 60, RELOAD_END: 14, COOLDOWN: 11, CAN_AUTO: True, DAMAGE: 24, DECAY: 0.92, WEIGHT: 2,
		ACCURACY_BASE: 150, ACCURACY_SNEAK: 80, ACCURACY_WALK: 290, ACCURACY_SPRINT: 400, ACCURACY_JUMP: 800,
		SWITCH: 12, KICK: 5,
		PROJECTILE_SPEED: 3000, PROJECTILE_GRAVITY: 0, PROJECTILE_LIFETIME: 200, PROJECTILE_MODEL: "ray_gun",
		EXPLOSION_RADIUS: 3.5, EXPLOSION_DAMAGE: 32, EXPLOSION_DECAY: 0.80,
		PAP_STATS: {
			PAP_NAME: "Porter's X2 Ray Gun",
			CAPACITY: 30,
			REMAINING_BULLETS: 30,
			RELOAD_TIME: 45,
			RELOAD_END: 10,
			COOLDOWN: 9,
			ACCURACY_BASE: 110,
			ACCURACY_WALK: 210,
			ACCURACY_SPRINT: 280,
			ACCURACY_JUMP: 500,
			SWITCH: 9,
			PROJECTILE_SPEED: 3400,
			EXPLOSION_DAMAGE: 40,
			DAMAGE: [48, 56, 66, 78, 92],
		},
	},
	"sounds": gun_sounds("ray_gun", *GUN_SOUNDS, "playermid", pap_fire="ray_gun/fire")
}

