""" Shotgun stat tables. """
# Imports
from stewbeet import JsonDict

from ..casings import CASING_12GA3IN, CASING_12GA275IN
from ..keys import (
	ACCURACY_BASE,
	ACCURACY_JUMP,
	ACCURACY_SNEAK,
	ACCURACY_SPRINT,
	ACCURACY_WALK,
	BASE_WEAPON,
	CAPACITY,
	CASING_BINORMAL,
	CASING_MODEL,
	CASING_NORMAL,
	CASING_OFFSET,
	CASING_TANGENT,
	COOLDOWN,
	DAMAGE,
	DECAY,
	FIRE_MODE,
	KICK,
	PAP_NAME,
	PAP_STATS,
	PELLET_COUNT,
	RELOAD_TIME,
	REMAINING_BULLETS,
	SINGLE_RELOAD,
	SWITCH,
	WEIGHT,
)
from ..sounds import PUMP_SOUNDS, gun_sounds

# Constants
# Shotguns
SPAS12: JsonDict = {
	"stats": {
		BASE_WEAPON: "spas12", FIRE_MODE: "semi", SINGLE_RELOAD: True,
		CAPACITY: 8, RELOAD_TIME: 20, COOLDOWN: 16, PELLET_COUNT: 3, DAMAGE: 13, DECAY: 0.82, WEIGHT: 5,
		ACCURACY_BASE: 230, ACCURACY_SNEAK: 190, ACCURACY_WALK: 300, ACCURACY_SPRINT: 800, ACCURACY_JUMP: 1500,
		SWITCH: 25, KICK: 6, CASING_MODEL: CASING_12GA275IN, CASING_NORMAL: 25, CASING_TANGENT: 100, CASING_BINORMAL: -200,
		CASING_OFFSET: {"normal": (-0.35, -0.3, 0.7), "zoom": (-0.1, -0.3, 0.6)},
		PAP_STATS: {
			PAP_NAME: "SPAZ-24",
			CAPACITY: 12,
			REMAINING_BULLETS: 12,
			RELOAD_TIME: 14,
			COOLDOWN: 12,
			PELLET_COUNT: 4,
			ACCURACY_BASE: 170,
			ACCURACY_WALK: 220,
			ACCURACY_SPRINT: 550,
			ACCURACY_JUMP: 1200,
			SWITCH: 18,
			DAMAGE: [26, 31, 37, 44, 52],
		},
	},
	"sounds": gun_sounds("spas12", "fire", "pap_fire", "fire_alt", "reload", "pump", crack="largest")
}

M500: JsonDict = {
	"stats": {
		BASE_WEAPON: "m500", FIRE_MODE: "semi", SINGLE_RELOAD: True,
		CAPACITY: 5, RELOAD_TIME: 22, COOLDOWN: 18, PELLET_COUNT: 3, DAMAGE: 14, DECAY: 0.82, WEIGHT: 4,
		ACCURACY_BASE: 250, ACCURACY_SNEAK: 200, ACCURACY_WALK: 350, ACCURACY_SPRINT: 900, ACCURACY_JUMP: 1600,
		SWITCH: 20, KICK: 7, CASING_MODEL: CASING_12GA3IN, CASING_NORMAL: 25, CASING_TANGENT: 100, CASING_BINORMAL: -200,
		CASING_OFFSET: {"normal": (-0.35, -0.3, 0.7), "zoom": (-0.1, -0.3, 0.6)},
		PAP_STATS: {
			PAP_NAME: "Voice of Justice",
			CAPACITY: 8,
			REMAINING_BULLETS: 8,
			RELOAD_TIME: 16,
			COOLDOWN: 14,
			PELLET_COUNT: 4,
			ACCURACY_BASE: 180,
			ACCURACY_WALK: 240,
			ACCURACY_SPRINT: 600,
			ACCURACY_JUMP: 1200,
			SWITCH: 15,
			DAMAGE: [28, 33, 39, 46, 54],
		},
	},
	"sounds": gun_sounds("m500", *PUMP_SOUNDS, crack="largest")
}

M590: JsonDict = {
	"stats": {
		BASE_WEAPON: "m590", FIRE_MODE: "semi", SINGLE_RELOAD: True,
		CAPACITY: 8, RELOAD_TIME: 22, COOLDOWN: 19, PELLET_COUNT: 3, DAMAGE: 14, DECAY: 0.82, WEIGHT: 4,
		ACCURACY_BASE: 210, ACCURACY_SNEAK: 175, ACCURACY_WALK: 325, ACCURACY_SPRINT: 800, ACCURACY_JUMP: 1500,
		SWITCH: 35, KICK: 5, CASING_MODEL: CASING_12GA3IN, CASING_NORMAL: 50, CASING_TANGENT: 80, CASING_BINORMAL: -220,
		CASING_OFFSET: {"normal": (-0.35, -0.27, 0.7), "zoom": (-0.1, -0.25, 0.6)},
		PAP_STATS: {
			PAP_NAME: "The Conversation Ender",
			CAPACITY: 12,
			REMAINING_BULLETS: 12,
			RELOAD_TIME: 16,
			COOLDOWN: 14,
			PELLET_COUNT: 4,
			ACCURACY_BASE: 155,
			ACCURACY_WALK: 220,
			ACCURACY_SPRINT: 520,
			ACCURACY_JUMP: 1200,
			SWITCH: 26,
			DAMAGE: [28, 33, 39, 46, 54],
		},
	},
	"sounds": gun_sounds("m590", *PUMP_SOUNDS, crack="largest")
}

