""" Submachine gun stat tables. """
# Imports
from stewbeet import JsonDict

from ..casings import CASING_9X19MM, CASING_45ACP, CASING_46X30MM, CASING_762X25MM
from ..keys import (
	ACCURACY_BASE,
	ACCURACY_JUMP,
	ACCURACY_SNEAK,
	ACCURACY_SPRINT,
	ACCURACY_WALK,
	BASE_WEAPON,
	BURST,
	CAN_AUTO,
	CAN_BURST,
	CAPACITY,
	CASING_BINORMAL,
	CASING_MODEL,
	CASING_NORMAL,
	CASING_OFFSET,
	CASING_TANGENT,
	COOLDOWN,
	DAMAGE,
	DECAY,
	FIRE_MODE,
	KICK,
	PAP_NAME,
	PAP_STATS,
	RELOAD_END,
	RELOAD_MID,
	RELOAD_TIME,
	REMAINING_BULLETS,
	SWITCH,
	WEIGHT,
)
from ..sounds import GUN_SOUNDS, gun_sounds

# Constants
# SMGS
MP5: JsonDict = {
	"stats": {
		BASE_WEAPON: "mp5", FIRE_MODE: "auto",
		CAPACITY: 30, RELOAD_TIME: 60, RELOAD_MID: 25, RELOAD_END: 5, COOLDOWN: 2, BURST: 2, CAN_BURST: True, CAN_AUTO: True, DAMAGE: 10, DECAY: 0.92, WEIGHT: 6,
		ACCURACY_BASE: 100, ACCURACY_SNEAK: 60, ACCURACY_WALK: 200, ACCURACY_SPRINT: 450, ACCURACY_JUMP: 1000,
		SWITCH: 15, KICK: 1, CASING_MODEL: CASING_9X19MM, CASING_NORMAL: 225, CASING_TANGENT: 10, CASING_BINORMAL: -275,
		CASING_OFFSET: {"normal": (-0.38, -0.35, 0.7), "zoom": (-0.05, -0.25, 0.5)},
		PAP_STATS: {
			PAP_NAME: "MP115 Kollider",
			CAPACITY: 42,
			REMAINING_BULLETS: 42,
			RELOAD_TIME: 45,
			RELOAD_MID: 20,
			RELOAD_END: 4,
			COOLDOWN: 1,
			ACCURACY_BASE: 80,
			ACCURACY_WALK: 150,
			ACCURACY_SPRINT: 320,
			ACCURACY_JUMP: 500,
			SWITCH: 11,
			DAMAGE: [20, 23, 27, 32, 38],
		},
	},
	"sounds": gun_sounds("mp5", *GUN_SOUNDS, "playermid", crack="tiny")
}

MAC10: JsonDict = {
	"stats": {
		BASE_WEAPON: "mac10", FIRE_MODE: "auto",
		CAPACITY: 30, RELOAD_TIME: 50, RELOAD_MID: 38, RELOAD_END: 10, COOLDOWN: 1, BURST: 4, CAN_BURST: True, CAN_AUTO: True, DAMAGE: 11, DECAY: 0.88, WEIGHT: 6,
		ACCURACY_BASE: 220, ACCURACY_SNEAK: 150, ACCURACY_WALK: 330, ACCURACY_SPRINT: 400, ACCURACY_JUMP: 800,
		SWITCH: 10, KICK: 2, CASING_MODEL: CASING_45ACP, CASING_NORMAL: 125, CASING_TANGENT: -25, CASING_BINORMAL: -175,
		CASING_OFFSET: {"normal": (-0.4, -0.35, 0.7), "zoom": (-0.05, -0.25, 0.5)},
		PAP_STATS: {
			PAP_NAME: "Mac Attack",
			CAPACITY: 45,
			REMAINING_BULLETS: 45,
			RELOAD_TIME: 40,
			RELOAD_MID: 28,
			RELOAD_END: 8,
			ACCURACY_BASE: 165,
			ACCURACY_WALK: 250,
			ACCURACY_SPRINT: 300,
			ACCURACY_JUMP: 500,
			SWITCH: 8,
			DAMAGE: [22, 25, 29, 34, 40],
		},
	},
	"sounds": gun_sounds("mac10", *GUN_SOUNDS, "playermid", crack="tiny")
}

MP7: JsonDict = {
	"stats": {
		BASE_WEAPON: "mp7", FIRE_MODE: "auto",
		CAPACITY: 40, RELOAD_TIME: 55, RELOAD_END: 15, COOLDOWN: 2, BURST: 3, CAN_BURST: True, CAN_AUTO: True, DAMAGE: 12, DECAY: 0.95, WEIGHT: 6,
		ACCURACY_BASE: 150, ACCURACY_SNEAK: 50, ACCURACY_WALK: 250, ACCURACY_SPRINT: 480, ACCURACY_JUMP: 1500,
		SWITCH: 20, KICK: 2, CASING_MODEL: CASING_46X30MM, CASING_NORMAL: 10, CASING_TANGENT: -50, CASING_BINORMAL: -275,
		CASING_OFFSET: {"normal": (-0.45, -0.4, 0.7), "zoom": (-0.05, -0.4, 0.5)},
		PAP_STATS: {
			PAP_NAME: "MP-Heaven",
			CAPACITY: 55,
			REMAINING_BULLETS: 55,
			RELOAD_TIME: 42,
			RELOAD_END: 10,
			COOLDOWN: 1,
			ACCURACY_BASE: 110,
			ACCURACY_WALK: 180,
			ACCURACY_SPRINT: 330,
			ACCURACY_JUMP: 1200,
			SWITCH: 14,
			DAMAGE: [24, 28, 32, 37, 43],
		},
	},
	"sounds": gun_sounds("mp7", *GUN_SOUNDS, crack="small")
}

PPSH41: JsonDict = {
	"stats": {
		BASE_WEAPON: "ppsh41", FIRE_MODE: "auto",
		CAPACITY: 71, RELOAD_TIME: 100, RELOAD_MID: 70, RELOAD_END: 16, COOLDOWN: 1, BURST: 4, CAN_BURST: True, CAN_AUTO: True, DAMAGE: 10, DECAY: 0.92, WEIGHT: 5,
		ACCURACY_BASE: 175, ACCURACY_SNEAK: 125, ACCURACY_WALK: 400, ACCURACY_SPRINT: 700, ACCURACY_JUMP: 1500,
		SWITCH: 40, KICK: 2, CASING_MODEL: CASING_762X25MM, CASING_NORMAL: 300, CASING_TANGENT: -50, CASING_BINORMAL: -25,
		CASING_OFFSET: {"normal": (-0.38, -0.2, 0.7), "zoom": (0.0, 0.0, 0.5)},
		PAP_STATS: {
			PAP_NAME: "The Reaper",
			CAPACITY: 90,
			REMAINING_BULLETS: 90,
			RELOAD_TIME: 75,
			RELOAD_MID: 48,
			RELOAD_END: 12,
			ACCURACY_BASE: 135,
			ACCURACY_WALK: 290,
			ACCURACY_SPRINT: 500,
			ACCURACY_JUMP: 1200,
			SWITCH: 30,
			DAMAGE: [20, 23, 27, 32, 38],
		},
	},
	"sounds": gun_sounds("ppsh41", *GUN_SOUNDS, "playermid", crack="tiny")
}

STEN: JsonDict = {
	"stats": {
		BASE_WEAPON: "sten", FIRE_MODE: "auto",
		CAPACITY: 32, RELOAD_TIME: 58, RELOAD_MID: 40, RELOAD_END: 10, COOLDOWN: 3, BURST: 2, CAN_BURST: True, CAN_AUTO: True, DAMAGE: 11, DECAY: 0.92, WEIGHT: 7,
		ACCURACY_BASE: 200, ACCURACY_SNEAK: 100, ACCURACY_WALK: 400, ACCURACY_SPRINT: 800, ACCURACY_JUMP: 1500,
		SWITCH: 25, KICK: 3, CASING_MODEL: CASING_9X19MM, CASING_NORMAL: 200, CASING_TANGENT: -50, CASING_BINORMAL: -200,
		CASING_OFFSET: {"normal": (-0.4, -0.35, 0.7), "zoom": (-0.05, -0.25, 0.5)},
		PAP_STATS: {
			PAP_NAME: "Sten & Deliver",
			CAPACITY: 45,
			REMAINING_BULLETS: 45,
			RELOAD_TIME: 44,
			RELOAD_MID: 28,
			RELOAD_END: 8,
			COOLDOWN: 2,
			ACCURACY_BASE: 150,
			ACCURACY_WALK: 280,
			ACCURACY_SPRINT: 520,
			ACCURACY_JUMP: 1200,
			SWITCH: 18,
			DAMAGE: [22, 26, 30, 35, 41],
		},
	},
	"sounds": gun_sounds("sten", *GUN_SOUNDS, "playermid", crack="tiny")
}

