""" Sniper and marksman rifle stat tables. """
# Imports
from stewbeet import JsonDict

from ..casings import CASING_50BMG, CASING_338LAPUA, CASING_762X54MM
from ..keys import (
	ACCURACY_BASE,
	ACCURACY_JUMP,
	ACCURACY_SNEAK,
	ACCURACY_SPRINT,
	ACCURACY_WALK,
	BASE_WEAPON,
	CAPACITY,
	CASING_BINORMAL,
	CASING_MODEL,
	CASING_NORMAL,
	CASING_OFFSET,
	CASING_TANGENT,
	COOLDOWN,
	DAMAGE,
	DECAY,
	FIRE_MODE,
	KICK,
	PAP_NAME,
	PAP_STATS,
	RELOAD_END,
	RELOAD_MID,
	RELOAD_TIME,
	REMAINING_BULLETS,
	SINGLE_RELOAD,
	SPEED_MULTIPLY_BASE,
	SWITCH,
	WEIGHT,
)
from ..sounds import GUN_SOUNDS, gun_sounds

# Constants
# Snipers
SVD: JsonDict = {
	"stats": {
		BASE_WEAPON: "svd", FIRE_MODE: "semi",
		CAPACITY: 10, RELOAD_TIME: 73, RELOAD_MID: 40, RELOAD_END: 10, COOLDOWN: 5, DAMAGE: 27, DECAY: 0.95, WEIGHT: 6, SPEED_MULTIPLY_BASE: -0.08,
		ACCURACY_BASE: 350, ACCURACY_SNEAK: 5, ACCURACY_WALK: 700, ACCURACY_SPRINT: 1500, ACCURACY_JUMP: 3000,
		SWITCH: 40, KICK: 4, CASING_MODEL: CASING_762X54MM, CASING_NORMAL: 150, CASING_TANGENT: -150, CASING_BINORMAL: -175,
		CASING_OFFSET: {"normal": (-0.3, -0.27, 0.7), "zoom": (-0.05, -0.25, 0.5)},
		PAP_STATS: {
			PAP_NAME: "Sudden Violence Device",
			CAPACITY: 14,
			REMAINING_BULLETS: 14,
			RELOAD_TIME: 55,
			RELOAD_MID: 30,
			RELOAD_END: 8,
			COOLDOWN: 4,
			ACCURACY_BASE: 250,
			ACCURACY_WALK: 450,
			ACCURACY_SPRINT: 1000,
			ACCURACY_JUMP: 2000,
			SWITCH: 30,
			DAMAGE: [54, 62, 72, 84, 98],
		},
	},
	"sounds": gun_sounds("svd", *GUN_SOUNDS, "playermid", crack="large")
}

M82: JsonDict = {
	"stats": {
		BASE_WEAPON: "m82", FIRE_MODE: "semi",
		CAPACITY: 10, RELOAD_TIME: 80, RELOAD_MID: 50, RELOAD_END: 15, COOLDOWN: 10, DAMAGE: 55, DECAY: 0.90, WEIGHT: 3, SPEED_MULTIPLY_BASE: -0.12,
		ACCURACY_BASE: 450, ACCURACY_SNEAK: 12, ACCURACY_WALK: 800, ACCURACY_SPRINT: 1500, ACCURACY_JUMP: 3000,
		SWITCH: 50, KICK: 5, CASING_MODEL: CASING_50BMG, CASING_NORMAL: 50, CASING_TANGENT: -25, CASING_BINORMAL: -225,
		CASING_OFFSET: {"normal": (-0.28, -0.3, 0.7), "zoom": (-0.1, -0.25, 0.6)},
		PAP_STATS: {
			PAP_NAME: "Macro Annihilator",
			CAPACITY: 12,
			REMAINING_BULLETS: 12,
			RELOAD_TIME: 62,
			RELOAD_MID: 38,
			RELOAD_END: 10,
			COOLDOWN: 8,
			ACCURACY_BASE: 320,
			ACCURACY_WALK: 500,
			ACCURACY_SPRINT: 1100,
			ACCURACY_JUMP: 2000,
			SWITCH: 38,
			DAMAGE: [110, 126, 144, 165, 190],
		},
	},
	"sounds": gun_sounds("m82", *GUN_SOUNDS, "playermid", crack="largest")
}

MOSIN: JsonDict = {
	"stats": {
		BASE_WEAPON: "mosin", FIRE_MODE: "semi", SINGLE_RELOAD: True,
		CAPACITY: 5, RELOAD_TIME: 20, RELOAD_MID: 15, COOLDOWN: 40, DAMAGE: 29, DECAY: 0.95, WEIGHT: 4, SPEED_MULTIPLY_BASE: -0.09,
		ACCURACY_BASE: 150, ACCURACY_SNEAK: 3, ACCURACY_WALK: 175, ACCURACY_SPRINT: 1000, ACCURACY_JUMP: 1500,
		SWITCH: 25, KICK: 4, CASING_MODEL: CASING_762X54MM, CASING_NORMAL: 100, CASING_TANGENT: -50, CASING_BINORMAL: -100,
		CASING_OFFSET: {"normal": (-0.35, -0.2, 0.6), "zoom": (-0.05, -0.2, 0.4)},
		PAP_STATS: {
			PAP_NAME: "Marksmen's Old Silent Infantry",
			CAPACITY: 7,
			REMAINING_BULLETS: 7,
			RELOAD_TIME: 14,
			RELOAD_MID: 10,
			COOLDOWN: 28,
			ACCURACY_BASE: 110,
			ACCURACY_WALK: 130,
			ACCURACY_SPRINT: 700,
			ACCURACY_JUMP: 1200,
			SWITCH: 18,
			DAMAGE: [58, 68, 80, 94, 111],
		},
	},
	"sounds": gun_sounds("mosin", *GUN_SOUNDS, "cycle", crack="large")
}

M24: JsonDict = {
	"stats": {
		BASE_WEAPON: "m24", FIRE_MODE: "semi", SINGLE_RELOAD: True,
		CAPACITY: 5, RELOAD_TIME: 25, RELOAD_MID: 14, COOLDOWN: 45, DAMAGE: 36, DECAY: 0.92, WEIGHT: 4, SPEED_MULTIPLY_BASE: -0.1,
		ACCURACY_BASE: 350, ACCURACY_SNEAK: 1, ACCURACY_WALK: 700, ACCURACY_SPRINT: 1500, ACCURACY_JUMP: 3000,
		SWITCH: 39, KICK: 4, CASING_MODEL: CASING_338LAPUA, CASING_NORMAL: 100, CASING_TANGENT: -50, CASING_BINORMAL: -100,
		CASING_OFFSET: {"normal": (-0.35, -0.2, 0.6), "zoom": (-0.05, -0.2, 0.4)},
		PAP_STATS: {
			PAP_NAME: "Isolator of Judgment",
			CAPACITY: 7,
			REMAINING_BULLETS: 7,
			RELOAD_TIME: 18,
			RELOAD_MID: 10,
			COOLDOWN: 32,
			ACCURACY_BASE: 250,
			ACCURACY_WALK: 420,
			ACCURACY_SPRINT: 1000,
			ACCURACY_JUMP: 2000,
			SWITCH: 28,
			DAMAGE: [72, 84, 98, 114, 132],
		},
	},
	"sounds": gun_sounds("m24", *GUN_SOUNDS, "cycle", crack="largest")
}

