""" Launcher and LMG stat tables. """
# Imports
from stewbeet import JsonDict

from ..casings import CASING_556X45MM, CASING_762X39MM
from ..keys import (
	ACCURACY_BASE,
	ACCURACY_JUMP,
	ACCURACY_SNEAK,
	ACCURACY_SPRINT,
	ACCURACY_WALK,
	BASE_WEAPON,
	BURST,
	CAN_AUTO,
	CAN_BURST,
	CAPACITY,
	CASING_BINORMAL,
	CASING_MODEL,
	CASING_NORMAL,
	CASING_OFFSET,
	CASING_TANGENT,
	COOLDOWN,
	DAMAGE,
	DECAY,
	EXPLOSION_DAMAGE,
	EXPLOSION_DECAY,
	EXPLOSION_RADIUS,
	FIRE_MODE,
	KICK,
	PAP_NAME,
	PAP_STATS,
	PROJECTILE_GRAVITY,
	PROJECTILE_LIFETIME,
	PROJECTILE_MODEL,
	PROJECTILE_SPEED,
	RELOAD_END,
	RELOAD_MID,
	RELOAD_TIME,
	REMAINING_BULLETS,
	SPEED_MULTIPLY_BASE,
	SWITCH,
	WEIGHT,
)
from ..sounds import GUN_SOUNDS, gun_sounds

# Constants
# Special
RPG7: JsonDict = {
	"stats": {
		BASE_WEAPON: "rpg7", FIRE_MODE: "semi",
		CAPACITY: 1, RELOAD_TIME: 110, RELOAD_END: 20, COOLDOWN: 10, DAMAGE: 30, DECAY: 1.00, WEIGHT: 4, SPEED_MULTIPLY_BASE: -0.14,
		ACCURACY_BASE: 250, ACCURACY_SNEAK: 100, ACCURACY_WALK: 300, ACCURACY_SPRINT: 300, ACCURACY_JUMP: 300,
		SWITCH: 55, KICK: 6,
		PROJECTILE_SPEED: 1500, PROJECTILE_GRAVITY: 0, PROJECTILE_LIFETIME: 200, PROJECTILE_MODEL: "rpg7_rocket",
		EXPLOSION_RADIUS: 6, EXPLOSION_DAMAGE: 30, EXPLOSION_DECAY: 0.80,
		PAP_STATS: {
			PAP_NAME: "Rocket Propelled Grievance",
			FIRE_MODE: "auto",
			CAN_AUTO: True,
			CAPACITY: 8,
			RELOAD_TIME: 80,
			RELOAD_END: 14,
			COOLDOWN: 5,
			SWITCH: 40,
			PROJECTILE_SPEED: 1800,
			EXPLOSION_RADIUS: 7,
			EXPLOSION_DAMAGE: 42,
			DAMAGE: [60, 75, 93, 113],
		},
	},
	"sounds": gun_sounds("rpg7", *GUN_SOUNDS, handling_endgrab="rpg7/handling/rpg7_endgrab", handling_fetch="rpg7/handling/rpg7_fetch", handling_load="rpg7/handling/rpg7_load", crack="rocket")
}

RPK: JsonDict = {
	"stats": {
		BASE_WEAPON: "rpk", FIRE_MODE: "auto",
		CAPACITY: 75, RELOAD_TIME: 115, RELOAD_MID: 60, RELOAD_END: 20, COOLDOWN: 2, BURST: 2, CAN_BURST: True, CAN_AUTO: True, DAMAGE: 15, DECAY: 0.90, WEIGHT: 3, SPEED_MULTIPLY_BASE: -0.11,
		ACCURACY_BASE: 470, ACCURACY_SNEAK: 80, ACCURACY_WALK: 900, ACCURACY_SPRINT: 1500, ACCURACY_JUMP: 3000,
		SWITCH: 55, KICK: 3, CASING_MODEL: CASING_762X39MM, CASING_NORMAL: 200, CASING_TANGENT: 50, CASING_BINORMAL: -200,
		CASING_OFFSET: {"normal": (-0.35, -0.28, 0.7), "zoom": (-0.05, -0.25, 0.5)},
		PAP_STATS: {
			PAP_NAME: "R115 Resonator",
			CAPACITY: 100,
			REMAINING_BULLETS: 100,
			RELOAD_TIME: 84,
			RELOAD_MID: 45,
			RELOAD_END: 14,
			COOLDOWN: 1,
			ACCURACY_BASE: 320,
			ACCURACY_WALK: 650,
			ACCURACY_SPRINT: 1100,
			ACCURACY_JUMP: 2000,
			SWITCH: 40,
			DAMAGE: [30, 34, 39, 45, 52],
		},
	},
	"sounds": gun_sounds("rpk", *GUN_SOUNDS, "playermid", crack="medium")
}

M249: JsonDict = {
	"stats": {
		BASE_WEAPON: "m249", FIRE_MODE: "auto",
		CAPACITY: 150, RELOAD_TIME: 175, RELOAD_MID: 110, RELOAD_END: 30, COOLDOWN: 2, BURST: 2, CAN_BURST: True, CAN_AUTO: True, DAMAGE: 13, DECAY: 0.92, WEIGHT: 3, SPEED_MULTIPLY_BASE: -0.15,
		ACCURACY_BASE: 300, ACCURACY_SNEAK: 60, ACCURACY_WALK: 1500, ACCURACY_SPRINT: 2500, ACCURACY_JUMP: 4000,
		SWITCH: 70, KICK: 2, CASING_MODEL: CASING_556X45MM, CASING_NORMAL: -50, CASING_TANGENT: 0, CASING_BINORMAL: -250,
		CASING_OFFSET: {"normal": (-0.35, -0.34, 0.7), "zoom": (0.0, -0.3, 0.7)},
		PAP_STATS: {
			PAP_NAME: "Endless Barrage",
			CAPACITY: 180,
			REMAINING_BULLETS: 180,
			RELOAD_TIME: 120,
			RELOAD_MID: 70,
			RELOAD_END: 20,
			COOLDOWN: 1,
			ACCURACY_BASE: 240,
			ACCURACY_WALK: 900,
			ACCURACY_SPRINT: 1500,
			ACCURACY_JUMP: 3000,
			SWITCH: 50,
			DAMAGE: [26, 30, 35, 41, 48],
		},
	},
	"sounds": gun_sounds("m249", *GUN_SOUNDS, "playermid", crack="medium")
}

